noteMidiDB = {
    "C8": 88,
    "B#7": 88,
    'Cb8': 87,
    "B7": 87,
    "Bb7": 86,
    "A#7": 86,
    "A7": 85,
    "Ab7": 84,
    "G#7": 84,
    "G7": 83,
    "Gb7": 82,
    "F#7": 82,
    "F7": 81,
    "E#7": 81,
    "Fb7": 80,
    "E7": 80,
    "Eb7": 79,
    "D#7": 79,
    "D7": 78,
    "Db7": 77,
    "C#7": 77,
    "C7": 76,
    "B#7": 76,
    "Cb7": 75,
    "B6": 75,
    "Bb6": 74,
    "A#6": 74,
    "A6": 73,
    "Ab6": 72,
    "G#6": 72,
    "G6": 71,
    "Gb6": 70,
    "F#6": 70,
    "F6": 69,
    "E#6": 69,
    "Fb6": 68,
    "E6": 68,
    "Eb6": 67,
    "D#6": 67,
    "D6": 66,
    "Db6": 65,
    "C#6": 65,
    "C6": 64,
    "B#5": 64,
    "Cb6": 63,
    "B5": 63,
    "Bb5": 62,
    "A#5": 62,
    "A5": 61,
    "Ab5": 60,
    "G#5": 60,
    "G5": 59,
    "Gb5": 58,
    "F#5": 58,
    "F5": 57,
    "E#5": 57,
    "Fb5": 56,
    "E5": 56,
    "Eb5": 55,
    "D#5": 55,
    "D5": 54,
    "Db5": 53,
    "C#5": 53,
    "C5": 52,
    "B#4": 52,
    "Cb5": 51,
    "B4": 51,
    "Bb4": 50,
    "A#4": 50,
    "A4": 49,
    "Ab4": 48,
    "G#4": 48,
    "G4": 47,
    "Gb4": 46,
    "F#4": 46,
    "F4": 45,
    "E#4": 45,
    "Fb4": 44,
    "E4": 44,
    "Eb4": 43,
    "D#4": 43,
    "D4": 42,
    "Db4": 41,
    "C#4": 41,
    "C4": 40,
    "B#3": 40,
    "Cb4": 39,
    "B3": 39,
    "Bb3": 38,
    "A#3": 38,
    "A3": 37,
    "Ab3": 36,
    "G#3": 36,
    "G3": 35,
    "Gb3": 34,
    "F#3": 34,
    "F3": 33,
    "E#3": 33,
    "Fb3": 32,
    "E3": 32,
    "Eb3": 31,
    "D#3": 31,
    "D3": 30,
    "Db3": 29,
    "C#3": 29,
    "C3": 28,
    "B#2": 28,
    "Cb3": 27,
    "B2": 27,
    "Bb2": 26,
    "A#2": 26,
    "A2": 25,
    "Ab2": 24,
    "G#2": 24,
    "G2": 23,
    "Gb2": 22,
    "F#2": 22,
    "F2": 21,
    "E#2": 21,
    "Fb2": 20,
    "E2": 20,
    "Eb2": 19,
    "D#2": 19,
    "D2": 18,
    "Db2": 17,
    "C#2": 17,
    "C2": 16,
    "B#1": 16,
    "Cb2": 15,
    "B1": 15,
    "Bb1": 14,
    "A#1": 14,
    "A1": 13,
    "Ab1": 12,
    "G#1": 12,
    "G1": 11,
    "Gb1": 10,
    "F#1": 10,
    "F1": 9,
    "E#1": 9,
    "Fb1": 8,
    "E1": 8,
    "Eb1": 7,
    "D#1": 7,
    "D1": 6,
    "Db1": 5,
    "C#1": 5,
    "C1": 4,
    "B#0": 4,
    "Cb1": 3,
    "B0": 3,
    "Bb0": 2,
    "A#0": 2,
    "A0": 1,
}

note_number_to_name = {
    88: "C8",
    87: "B7",
    86: "Bb7",
    85: "A7",
    84: "Ab7",
    83: "G7",
    82: "F#7",
    81: "F7",
    80: "E7",
    79: "Eb7",
    78: "D7",
    77: "Db7",
    76: "C7",
    75: "B6",
    74: "Bb6",
    73: "A6",
    72: "Ab6",
    71: "G6",
    70: "F#6",
    69: "F6",
    68: "E6",
    67: "Eb6",
    66: "D6",
    65: "Db6",
    64: "C6",
    63: "B5",
    62: "Bb5",
    61: "A5",
    60: "Ab5",
    59: "G5",
    58: "F#5",
    57: "F5",
    56: "E5",
    55: "Eb5",
    54: "D5",
    53: "Db5",
    52: "C5",
    51: "B4",
    50: "Bb4",
    49: "A4",
    48: "Ab4",
    47: "G4",
    46: "F#4",
    45: "F4",
    44: "E4",
    43: "Eb4",
    42: "D4",
    41: "Db4",
    40: "C4",
    39: "B3",
    38: "Bb3",
    37: "A3",
    36: "Ab3",
    35: "G3",
    34: "F#3",
    33: "F3",
    32: "E3",
    31: "Eb3",
    30: "D3",
    29: "Db3",
    28: "C3",
    27: "B2",
    26: "Bb2",
    25: "A2",
    24: "Ab2",
    23: "G2",
    22: "F#2",
    21: "F2",
    20: "E2",
    19: "Eb2",
    18: "D2",
    17: "Db2",
    16: "C2",
    15: "B1",
    14: "Bb1",
    13: "A1",
    12: "Ab1",
    11: "G1",
    10: "F#1",
    9: "F1",
    8: "E1",
    7: "Eb1",
    6: "D1",
    5: "Db1",
    4: "C1",
    3: "B0",
    2: "Bb0",
    1: "A0",
}

note_number_to_xml_flat = {
    88: {"step": "C", "alter": "", "octave": "8"},
    87: {"step": "B", "alter": "", "octave": "7"},
    86: {"step": "B", "alter": "-1", "octave": "7"},
    85: {"step": "A", "alter": "", "octave": "7"},  
    84: {"step": "A", "alter": "-1", "octave": "7"},
    83: {"step": "G", "alter": "", "octave": "7"},  
    82: {"step": "G", "alter": "-1", "octave": "7"},
    81: {"step": "F", "alter": "", "octave": "7"},  
    80: {"step": "E", "alter": "", "octave": "7"},  
    79: {"step": "E", "alter": "-1", "octave": "7"},
    78: {"step": "D", "alter": "", "octave": "7"},  
    77: {"step": "D", "alter": "-1", "octave": "7"},
    76: {"step": "C", "alter": "", "octave": "7"},  
    75: {"step": "B", "alter": "", "octave": "6"},  
    74: {"step": "B", "alter": "-1", "octave": "6"},
    73: {"step": "A", "alter": "", "octave": "6"},  
    72: {"step": "A", "alter": "-1", "octave": "6"},
    71: {"step": "G", "alter": "", "octave": "6"},  
    70: {"step": "G", "alter": "-1", "octave": "6"},
    69: {"step": "F", "alter": "", "octave": "6"},  
    68: {"step": "E", "alter": "", "octave": "6"},  
    67: {"step": "E", "alter": "-1", "octave": "6"},
    66: {"step": "D", "alter": "", "octave": "6"},  
    65: {"step": "D", "alter": "-1", "octave": "6"},
    64: {"step": "C", "alter": "", "octave": "6"},  
    63: {"step": "B", "alter": "", "octave": "5"},  
    62: {"step": "B", "alter": "-1", "octave": "5"},
    61: {"step": "A", "alter": "", "octave": "5"},  
    60: {"step": "A", "alter": "-1", "octave": "5"},
    59: {"step": "G", "alter": "", "octave": "5"},  
    58: {"step": "G", "alter": "-1", "octave": "5"},
    57: {"step": "F", "alter": "", "octave": "5"},  
    56: {"step": "E", "alter": "", "octave": "5"},  
    55: {"step": "E", "alter": "-1", "octave": "5"},
    54: {"step": "D", "alter": "", "octave": "5"},  
    53: {"step": "D", "alter": "-1", "octave": "5"},
    52: {"step": "C", "alter": "", "octave": "5"},  
    51: {"step": "B", "alter": "", "octave": "4"},  
    50: {"step": "B", "alter": "-1", "octave": "4"},
    49: {"step": "A", "alter": "", "octave": "4"},  
    48: {"step": "A", "alter": "-1", "octave": "4"},
    47: {"step": "G", "alter": "", "octave": "4"},  
    46: {"step": "G", "alter": "-1", "octave": "4"},
    45: {"step": "F", "alter": "", "octave": "4"},  
    44: {"step": "E", "alter": "", "octave": "4"},  
    43: {"step": "E", "alter": "-1", "octave": "4"},
    42: {"step": "D", "alter": "", "octave": "4"},  
    41: {"step": "D", "alter": "-1", "octave": "4"},
    40: {"step": "C", "alter": "", "octave": "4"},  
    39: {"step": "B", "alter": "", "octave": "3"},  
    38: {"step": "B", "alter": "-1", "octave": "3"},
    37: {"step": "A", "alter": "", "octave": "3"},  
    36: {"step": "A", "alter": "-1", "octave": "3"},
    35: {"step": "G", "alter": "", "octave": "3"},  
    34: {"step": "G", "alter": "-1", "octave": "3"},
    33: {"step": "F", "alter": "", "octave": "3"},  
    32: {"step": "E", "alter": "", "octave": "3"},  
    31: {"step": "E", "alter": "-1", "octave": "3"},
    30: {"step": "D", "alter": "", "octave": "3"},  
    29: {"step": "D", "alter": "-1", "octave": "3"},
    28: {"step": "C", "alter": "", "octave": "3"},  
    27: {"step": "B", "alter": "", "octave": "2"},  
    26: {"step": "B", "alter": "-1", "octave": "2"},
    25: {"step": "A", "alter": "", "octave": "2"},  
    24: {"step": "A", "alter": "-1", "octave": "2"},
    23: {"step": "G", "alter": "", "octave": "2"},  
    22: {"step": "G", "alter": "-1", "octave": "2"},
    21: {"step": "F", "alter": "", "octave": "2"},  
    20: {"step": "E", "alter": "", "octave": "2"},  
    19: {"step": "E", "alter": "-1", "octave": "2"},
    18: {"step": "D", "alter": "", "octave": "2"},  
    17: {"step": "D", "alter": "-1", "octave": "2"},
    16: {"step": "C", "alter": "", "octave": "2"},  
    15: {"step": "B", "alter": "", "octave": "1"},  
    14: {"step": "B", "alter": "-1", "octave": "1"},
    13: {"step": "A", "alter": "", "octave": "1"},  
    12: {"step": "A", "alter": "-1", "octave": "1"},
    11: {"step": "G", "alter": "", "octave": "1"},  
    10: {"step": "G", "alter": "-1", "octave": "1"},
     9: {"step": "F", "alter": "", "octave": "1"},  
     8: {"step": "E", "alter": "", "octave": "1"},  
     7: {"step": "E", "alter": "-1", "octave": "1"},
     6: {"step": "D", "alter": "", "octave": "1"},  
     5: {"step": "D", "alter": "-1", "octave": "1"},
     4: {"step": "C", "alter": "", "octave": "1"},  
     3: {"step": "B", "alter": "", "octave": "0"},  
     2: {"step": "B", "alter": "-1", "octave": "0"},
     1: {"step": "A", "alter": "", "octave": "0"},  
}

note_number_to_xml_sharp = {
    88: {"step": "C", "alter": "", "octave": "8"},
    87: {"step": "B", "alter": "", "octave": "7"},
    86: {"step": "A", "alter": "1", "octave": "7"},
    85: {"step": "A", "alter": "", "octave": "7"},
    84: {"step": "G", "alter": "1", "octave": "7"},
    83: {"step": "G", "alter": "", "octave": "7"}, 
    82: {"step": "F", "alter": "1", "octave": "7"},
    81: {"step": "F", "alter": "", "octave": "7"}, 
    80: {"step": "E", "alter": "", "octave": "7"}, 
    79: {"step": "D", "alter": "1", "octave": "7"},
    78: {"step": "D", "alter": "", "octave": "7"}, 
    77: {"step": "C", "alter": "1", "octave": "7"},
    76: {"step": "C", "alter": "", "octave": "7"}, 
    75: {"step": "B", "alter": "", "octave": "6"}, 
    74: {"step": "A", "alter": "1", "octave": "6"},
    73: {"step": "A", "alter": "", "octave": "6"}, 
    72: {"step": "G", "alter": "1", "octave": "6"},
    71: {"step": "G", "alter": "", "octave": "6"}, 
    70: {"step": "F", "alter": "1", "octave": "6"},
    69: {"step": "F", "alter": "", "octave": "6"}, 
    68: {"step": "E", "alter": "", "octave": "6"}, 
    67: {"step": "D", "alter": "1", "octave": "6"},
    66: {"step": "D", "alter": "", "octave": "6"}, 
    65: {"step": "C", "alter": "1", "octave": "6"},
    64: {"step": "C", "alter": "", "octave": "6"}, 
    63: {"step": "B", "alter": "", "octave": "5"}, 
    62: {"step": "A", "alter": "1", "octave": "5"},
    61: {"step": "A", "alter": "", "octave": "5"}, 
    60: {"step": "G", "alter": "1", "octave": "5"},
    59: {"step": "G", "alter": "", "octave": "5"}, 
    58: {"step": "F", "alter": "1", "octave": "5"},
    57: {"step": "F", "alter": "", "octave": "5"}, 
    56: {"step": "E", "alter": "", "octave": "5"}, 
    55: {"step": "D", "alter": "1", "octave": "5"},
    54: {"step": "D", "alter": "", "octave": "5"}, 
    53: {"step": "C", "alter": "1", "octave": "5"},
    52: {"step": "C", "alter": "", "octave": "5"}, 
    51: {"step": "B", "alter": "", "octave": "4"}, 
    50: {"step": "A", "alter": "1", "octave": "4"},
    49: {"step": "A", "alter": "", "octave": "4"}, 
    48: {"step": "G", "alter": "1", "octave": "4"},
    47: {"step": "G", "alter": "", "octave": "4"}, 
    46: {"step": "F", "alter": "1", "octave": "4"},
    45: {"step": "F", "alter": "", "octave": "4"}, 
    44: {"step": "E", "alter": "", "octave": "4"}, 
    43: {"step": "D", "alter": "1", "octave": "4"},
    42: {"step": "D", "alter": "", "octave": "4"}, 
    41: {"step": "C", "alter": "1", "octave": "4"},
    40: {"step": "C", "alter": "", "octave": "4"}, 
    39: {"step": "B", "alter": "", "octave": "3"}, 
    38: {"step": "A", "alter": "1", "octave": "3"},
    37: {"step": "A", "alter": "", "octave": "3"}, 
    36: {"step": "G", "alter": "1", "octave": "3"},
    35: {"step": "G", "alter": "", "octave": "3"}, 
    34: {"step": "F", "alter": "1", "octave": "3"},
    33: {"step": "F", "alter": "", "octave": "3"}, 
    32: {"step": "E", "alter": "", "octave": "3"}, 
    31: {"step": "D", "alter": "1", "octave": "3"},
    30: {"step": "D", "alter": "", "octave": "3"}, 
    29: {"step": "C", "alter": "1", "octave": "3"},
    28: {"step": "C", "alter": "", "octave": "3"}, 
    27: {"step": "B", "alter": "", "octave": "2"}, 
    26: {"step": "A", "alter": "1", "octave": "2"},
    25: {"step": "A", "alter": "", "octave": "2"}, 
    24: {"step": "G", "alter": "1", "octave": "2"},
    23: {"step": "G", "alter": "", "octave": "2"}, 
    22: {"step": "F", "alter": "1", "octave": "2"},
    21: {"step": "F", "alter": "", "octave": "2"}, 
    20: {"step": "E", "alter": "", "octave": "2"}, 
    19: {"step": "D", "alter": "1", "octave": "2"},
    18: {"step": "D", "alter": "", "octave": "2"}, 
    17: {"step": "C", "alter": "1", "octave": "2"},
    16: {"step": "C", "alter": "", "octave": "2"}, 
    15: {"step": "B", "alter": "", "octave": "1"}, 
    14: {"step": "A", "alter": "1", "octave": "1"},
    13: {"step": "A", "alter": "", "octave": "1"}, 
    12: {"step": "G", "alter": "1", "octave": "1"},
    11: {"step": "G", "alter": "", "octave": "1"}, 
    10: {"step": "F", "alter": "1", "octave": "1"},
    9: {"step": "F", "alter": "", "octave": "1"}, 
    8: {"step": "E", "alter": "", "octave": "1"}, 
    7: {"step": "D", "alter": "1", "octave": "1"},
    6: {"step": "D", "alter": "", "octave": "1"}, 
    5: {"step": "C", "alter": "1", "octave": "1"},
    4: {"step": "C", "alter": "", "octave": "1"}, 
    3: {"step": "B", "alter": "", "octave": "0"}, 
    2: {"step": "A", "alter": "1", "octave": "0"},
    1: {"step": "A", "alter": "", "octave": "0"},
}

key_sig_table = {
    "C+": "b",
    "C-": "b",
    "G+": "#",
    "G-": "b",
    "D+": "#",
    "D-": "b",
    "A+": "#",
    "A-": "b",
    "E+": "#",
    "E-": "#",
    "B+": "#",
    "B-": "#",
    "F#+": "#",
    "F#-": "#",
    "Gb+": "b",
    "Gb-": "b",
    "Db+": "b",
    "Db-": "b",
    "Ab+": "b",
    "Ab-": "b",
    "Eb+": "b",
    "Eb-": "b",
    "Bb+": "b",
    "Bb-": "b",
    "F+": "b",
    "F-": "b",

}

transpose_to_c = {
    "B#": {
        "up": 0,
        "down":0
    },
    "Cb": {
        "up": 1,
        "down": -11
    },
    "B": {
        "up": 1,
        "down": -11
    },
    "Bb": {
        "up": 2,
        "down": -10
    },
    "A#": {
        "up": 2,
        "down": -10
    },
    "Bbb": {
        "up": 3,
        "down": 9
    },
    "A": {
        "up": 3,
        "down": -9
    },
    "Ab": {
        "up": 4,
        "down": -8
    },
    "G#": {
        "up": 4,
        "down": -8
    },
    "G": {
        "up": 5,
        "down": -7 
    },
    "Gb": {
        "up": 6,
        "down": -6
    },
    "F#": {
        "up": 6,
        "down": -6
    },
    "F": {
        "up": 7,
        "down": -5
    },
    "E#": {
        "up": 7,
        "down": -5
    },
    "Fb": {
        "up": 8,
        "down": -4
    },
    "E": {
        "up": 8,
        "down": -4
    },
    "Eb": {
        "up": 9,
        "down": -3
    },
    "Ebb": {
        "up": 10,
        "down": 2
    },
    "D#": {
        "up": 9,
        "down": -3
    },
    "D": {
        "up": 10,
        "down": -2
    },
    "Db": {
        "up": 11,
        "down": -1
    },
    "C#": {
        "up": 11,
        "down": -1,
    },
    "C": {
        "up": 0,
        "down": 0,
    }
}

# https://en.wikipedia.org/wiki/Pitch_class#Integer_notation
chord_label_to_integer_notation = {
    'dominant': [0, 4, 7, 10], 
    'minor-seventh': [0, 3, 7, 10], 
    'minor-ninth': [0, 2, 3, 7, 10], 
    'minor-11th': [0, 2, 3, 5, 7, 10], 
    'minor-13th': [0, 2, 3, 7, 9, 10], 
    'dominant-11th': [0, 2, 4, 5, 7, 10], 
    'major-sixth': [0, 4, 7, 9], 
    'suspended-fourth': [0, 5, 7], 
    'major-ninth': [0, 2, 4, 7, 11], 
    'major-seventh': [0, 4, 7, 11], 
    'dominant-13th': [0, 2, 4, 7, 9, 10], 
    'dominant-ninth': [0, 2, 4, 7, 10], 
    'major': [0, 4, 7], 
    'major-minor': [0, 3, 7, 11], 
    'diminished': [0, 3, 6], 
    'half-diminished': [0, 3, 6, 10], 
    'augmented-seventh': [0, 4, 8, 10], 
    'minor': [0, 3, 7], 
    'diminished-seventh': [0, 3, 6, 9], 
    'minor-sixth': [0, 3, 7, 9], 
    'major-13th': [0, 2, 4, 7, 9, 11], 
    'augmented': [0, 4, 8], 
    'suspended-second': [0, 2, 7]
}

extensions_to_integer_notation = {
    "13": 9,
    "11": 5,
    "9": 2,
    "7": 10, # 7 usually refers to dominant 7 (b7)
    "6": 9,
    "5": 7,
    "4": 5,
    "3": 4,
    "2": 2
}

unwanted_chord_tones = {
    "major-seventh": [1, 3, 5, 8, 10],
    "minor-seventh": [1, 4, 6, 8, 11],
    "dominant": [],
    "major": [1, 3, 5, 6, 8, 10],
}

alter_dict = {
    "-2": "bb",
    "-1": "b",
    "0": "",
    "1": "#",
}